<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfcEntityCollection\Module'                             => __DIR__ . '/Module.php',
    'ZfcEntityCollection\Collection\AbstractCollection'      => __DIR__ . '/src/zfcEntityCollection/Collection/AbstractCollection.php',
    'zfcEntityCollection\Db\ResultSet\ResultSet'             => __DIR__ . '/src/zfcEntityCollection/Db/ResultSet/ResultSet.php',
    'ZfcEntityCollection\Entity\AbstractEntity'              => __DIR__ . '/src/zfcEntityCollection/Entity/AbstractEntity.php',
    'ZfcEntityCollection\Exception\InvalidArgumentException' => __DIR__ . '/src/zfcEntityCollection/Exception/InvalidArgumentException.php',
    'ZfcEntityCollection\Exception'                          => __DIR__ . '/src/zfcEntityCollection/Exception.php',
);