<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'mwEntityCollection\Exception'                          => __DIR__ . '/src/mwEntityCollection/Exception.php',
    'mwEntityCollection\Exception\InvalidArgumentException' => __DIR__ . '/src/mwEntityCollection/Exception/InvalidArgumentException.php',
    'mwEntityCollection\Exception\RuntimeException'         => __DIR__ . '/src/mwEntityCollection/Exception/RuntimeException.php',
    'mwEntityCollection\Exception\DomainException'          => __DIR__ . '/src/mwEntityCollection/Exception/DomainException.php',
    'mwEntityCollection\Collection\AbstractCollection'      => __DIR__ . '/src/mwEntityCollection/Collection/AbstractCollection.php',
    'mwEntityCollection\Entity\AbstractEntity'              => __DIR__ . '/src/mwEntityCollection/Entity/AbstractEntity.php',
    'mwEntityCollection\Module'                             => __DIR__ . '/Module.php',
);