<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MwEntityCollection\Module'                             => __DIR__ . '/Module.php',
    'MwEntityCollection\Collection\AbstractCollection'      => __DIR__ . '/src/MwEntityCollection/Collection/AbstractCollection.php',
    'MwEntityCollection\Db\ResultSet\ResultSet'             => __DIR__ . '/src/MwEntityCollection/Db/ResultSet/ResultSet.php',
    'MwEntityCollection\Entity\AbstractEntity'              => __DIR__ . '/src/MwEntityCollection/Entity/AbstractEntity.php',
    'MwEntityCollection\Exception\InvalidArgumentException' => __DIR__ . '/src/MwEntityCollection/Exception/InvalidArgumentException.php',
    'MwEntityCollection\Exception'                          => __DIR__ . '/src/MwEntityCollection/Exception.php',
);
